version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    command: yarn run start
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: pawful-db
      POSTGRES_HOST: db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
